// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjftrpxbbmvtdwzftgkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqZnRycHhiYm12dGR3emZ0Z2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNjM1MTMsImV4cCI6MjA3NzYzOTUxM30.hwqhz2gSnkBxoX285W9UnsGVzA9OXWGhocqaXFXd6vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});